# Generated by Django 3.1.6 on 2021-02-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210208_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumables',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='consumable',
            field=models.ManyToManyField(to='main_app.Consumables'),
        ),
        migrations.AddField(
            model_name='task',
            name='tool',
            field=models.ManyToManyField(to='main_app.Tool'),
        ),
    ]
