# Generated by Django 3.1.6 on 2021-02-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210208_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='img_url',
        ),
    ]
