# Generated by Django 3.1.6 on 2021-02-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210210_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maint_record',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.task'),
        ),
    ]
