# Generated by Django 3.1.6 on 2021-02-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210210_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
